spring.application.name=STUK-Acessos?
spring.datasource.url=jdbc:mysql://localhost:3306/STUK_Acessos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ezreal@21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver